classdef helpers
methods (Static)
    function S = loadData()
        P1 = helpers.readDataset('../data_part_1.csv'); % correct root for where data csv is located
        P2 = helpers.readDataset('../data_part_2.csv');

        [common_traits, tIdx1, tIdx2] = intersect(P1.trait_names, P2.trait_names);
        [common_wavelengths, wIdx1, wIdx2]  = intersect(P1.wave_lengths, P2.wave_lengths);

        T1c = P1.traits_data(:, tIdx1);  
        T2c = P2.traits_data(:, tIdx2);
        X1c = P1.spectra_data(:, wIdx1);
        X2c = P2.spectra_data(:, wIdx2);

        S = struct( ...
            'n_samples1', P1.n_samples, ...
            'n_samples2', P2.n_samples, ...
            'traits_common', {common_traits}, ...
            'n_traits1', numel(P1.trait_names), ...
            'n_traits2', numel(P2.trait_names), ...
            'waves_equal', isequal(P1.wave_lengths, P2.wave_lengths), ...
            'n_waves1', numel(P1.wave_lengths), ...
            'n_waves2', numel(P2.wave_lengths), ...
            'waves_common', common_wavelengths, ...
            'traits1_common', T1c, ...       
            'traits2_common', T2c, ...       
            'spectra1_common', X1c, ...      
            'spectra2_common', X2c, ...      
            'traits_merged', [T1c; T2c], ... 
            'spectra_merged', [X1c; X2c] ...  
        );
    end
end

methods (Static, Access = private)
    function P = readDataset(file)
        if ~isfile(file), error('File not found: %s', file); end

        T = readtable(file, 'ReadVariableNames', true, 'VariableNamingRule','preserve');
        T.Properties.VariableNames{1} = 'SampleID';

        v = string(T.Properties.VariableNames);
        isWavelength  = ~isnan(str2double(v));
        isTrait = ~isWavelength & v ~= "SampleID";

        trait_names  = cellstr(v(isTrait));
        wave_lengths = str2double(v(isWavelength));

        P = struct( ...
            'n_samples',   height(T), ...
            'trait_names', {trait_names}, ...
            'wave_lengths', wave_lengths, ...
            'traits_data',  table2array(T(:, isTrait)), ...
            'spectra_data', table2array(T(:, isWavelength)) );
    end
end
end